GuildSellsMonitoringMinimal_Data =
{
    ["EU Megaserver"] = 
    {
        ["@ventrill"] = 
        {
            ["$AccountWide"] = 
            {
                ["Account"] = 
                {
                    ["forTest"] = 
                    {
                        [742682] = 
                        {
                            ["name"] = "Style Page: Nord Carved Pauldrons",
                            ["quality"] = 5,

                            ["displayQuality"] = 5,
                            ["itemLink"] = "|H0:item:182466:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                            ["stackCount"] = 1,
                            ["currencyType"] = 1,
                            ["sellerName"] = "@ventrill",
                            ["purchasePricePerUnit"] = 5000,
                            ["slotIndex"] = 25,
                            ["timeRemaining"] = 2479363,
                            ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                            ["purchasePrice"] = 5000,
                        },
                        [726298] = 
                        {
                            ["name"] = "Style Page: Morningstar Frostwear Shoes",
                            ["quality"] = 5,
                            ["itemUniqueId"] = 2.8357143408,
                            ["displayQuality"] = 5,
                            ["itemLink"] = "|H0:item:199085:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                            ["stackCount"] = 1,
                            ["currencyType"] = 1,
                            ["sellerName"] = "@ventrill",
                            ["purchasePricePerUnit"] = 70000,
                            ["slotIndex"] = 3,
                            ["timeRemaining"] = 2479263,
                            ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                            ["purchasePrice"] = 70000,
                        },
                    },
                    ["version"] = 1,
                    ["sale"] = 
                    {
                        [585680] = 
                        {
                            [1] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506303,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                            [2] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506304,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                            [3] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506305,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                        },
                        [147954] = 
                        {
                        },
                        [726298] = 
                        {
                            [4] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506271,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                            [1] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:153737:5:1:0:0:0:18:255:4:81:33:0:0:0:0:0:0:0:0:0:330750|h|h",
                                ["itemId"] = 153737,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 280,
                                ["timeRemaining"] = 2506218,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 9240,
                            },
                            [2] = 
                            {
                                ["name"] = "Kuta",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:45854:24:21:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 45854,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 25,
                                ["purchasePricePerUnit"] = 4250,
                                ["timeRemaining"] = 2506265,
                                ["icon"] = "/esoui/art/icons/crafting_components_runestones_001.dds",
                                ["purchasePrice"] = 106250,
                            },
                            [3] = 
                            {
                                ["name"] = "Kuta",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:45854:24:21:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 45854,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 25,
                                ["purchasePricePerUnit"] = 4250,
                                ["timeRemaining"] = 2506266,
                                ["icon"] = "/esoui/art/icons/crafting_components_runestones_001.dds",
                                ["purchasePrice"] = 106250,
                            },
                        },
                        [742682] = 
                        {
                            [1] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Tomeshell Viscera",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198388:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 198388,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3450,
                                ["timeRemaining"] = 2504016,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarscroll002.dds",
                                ["purchasePrice"] = 3450,
                            },
                            [2] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:679:29:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7910000000,
                                ["timeRemaining"] = 2506149,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 44197,
                            },
                            [3] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:323:21:0:0:0:0:0:0:0:0:0:880000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 363.6360000000,
                                ["timeRemaining"] = 2506168,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 32000,
                            },
                            [4] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:385:29:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7910000000,
                                ["timeRemaining"] = 2506146,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 44197,
                            },
                            [5] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:540:23:0:0:0:0:0:0:0:0:0:897600|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 388.8890000000,
                                ["timeRemaining"] = 2506159,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 35000,
                            },
                            [6] = 
                            {
                                ["name"] = "Style Page: Y'ffre's Fallen-Wood Cuirass",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199053:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 199053,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 22500,
                                ["timeRemaining"] = 2503983,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 22500,
                            },
                            [7] = 
                            {
                                ["name"] = "Style Page: Opal Velidreth Sword",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:190108:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 190108,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 1950,
                                ["timeRemaining"] = 2503961,
                                ["icon"] = "/esoui/art/icons/quest_letter_002.dds",
                                ["purchasePrice"] = 1950,
                            },
                            [8] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Brains",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198382:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 198382,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 4750,
                                ["timeRemaining"] = 2504034,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarbrains001.dds",
                                ["purchasePrice"] = 4750,
                            },
                            [9] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Centipede",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198383:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 198383,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3500,
                                ["timeRemaining"] = 2504040,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarcentipedes002.dds",
                                ["purchasePrice"] = 3500,
                            },
                            [10] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:71059:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["itemId"] = 119693,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["timeRemaining"] = 2506026,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [11] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:71059:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["itemId"] = 119693,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["timeRemaining"] = 2506028,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [12] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:153737:5:1:0:0:0:18:255:4:92:33:0:0:0:0:0:0:0:0:0:346500|h|h",
                                ["itemId"] = 153737,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 280,
                                ["timeRemaining"] = 2506186,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 9800,
                            },
                            [13] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:64221:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["itemId"] = 119693,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["timeRemaining"] = 2506030,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [14] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:642:31:0:0:0:0:0:0:0:0:0:1122000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7860000000,
                                ["timeRemaining"] = 2506138,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 45000,
                            },
                            [15] = 
                            {
                                ["name"] = "Sealed Alchemy Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119703:5:1:0:0:0:199:8:11:2:0:0:0:0:0:0:0:0:0:0:50000|h|h",
                                ["itemId"] = 119703,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3400,
                                ["timeRemaining"] = 2506042,
                                ["icon"] = "/esoui/art/icons/master_writ_alchemy.dds",
                                ["purchasePrice"] = 17000,
                            },
                            [16] = 
                            {
                                ["name"] = "Sealed Alchemy Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119819:5:1:0:0:0:199:18:10:2:0:0:0:0:0:0:0:0:0:0:50000|h|h",
                                ["itemId"] = 119819,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3400,
                                ["timeRemaining"] = 2506048,
                                ["icon"] = "/esoui/art/icons/master_writ_alchemy.dds",
                                ["purchasePrice"] = 17000,
                            },
                            [17] = 
                            {
                                ["name"] = "Sealed Clothier Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:121532:6:1:0:0:0:28:194:5:38:15:128:0:0:0:0:0:0:0:0:811200|h|h",
                                ["itemId"] = 121532,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 250,
                                ["timeRemaining"] = 2505936,
                                ["icon"] = "/esoui/art/icons/master_writ_clothier.dds",
                                ["purchasePrice"] = 20250,
                            },
                            [18] = 
                            {
                                ["name"] = "Sealed Alchemy Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119696:5:1:0:0:0:199:2:11:21:0:0:0:0:0:0:0:0:0:0:50000|h|h",
                                ["itemId"] = 119696,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3400,
                                ["timeRemaining"] = 2506056,
                                ["icon"] = "/esoui/art/icons/master_writ_alchemy.dds",
                                ["purchasePrice"] = 17000,
                            },
                            [19] = 
                            {
                                ["name"] = "Style Page: Nord Carved Gauntlets",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182469:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182469,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 2500,
                                ["timeRemaining"] = 2503975,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 2500,
                            },
                            [20] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:148:32:0:0:0:0:0:0:0:0:0:1122000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7860000000,
                                ["timeRemaining"] = 2506141,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 45000,
                            },
                            [21] = 
                            {
                                ["name"] = "Style Page: Nord Carved Sabatons",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182467:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182467,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 7000,
                                ["timeRemaining"] = 2506099,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7000,
                            },
                            [22] = 
                            {
                                ["name"] = "Recipe: Lava Foot Soup-and-Saltrice",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 3,
                                ["itemLink"] = "|H0:item:96967:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 96967,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 27950,
                                ["timeRemaining"] = 2503915,
                                ["icon"] = "/esoui/art/icons/event_newlifefestival_2016_recipe.dds",
                                ["purchasePrice"] = 27950,
                            },
                            [23] = 
                            {
                                ["name"] = "Style Page: Nord Carved Pauldrons",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182466:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182466,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 7000,
                                ["timeRemaining"] = 2506105,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7000,
                            },
                            [24] = 
                            {
                                ["name"] = "Style Page: Nord Carved Cuirass",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182457:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182457,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 7500,
                                ["timeRemaining"] = 2506111,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [25] = 
                            {
                                ["name"] = "Breton Chamberstick, Short",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 3,
                                ["itemLink"] = "|H0:item:116376:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 116376,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 6250,
                                ["timeRemaining"] = 2505889,
                                ["icon"] = "/esoui/art/icons/housing_bre_lsb_candleholdershort001.dds",
                                ["purchasePrice"] = 6250,
                            },
                            [26] = 
                            {
                                ["name"] = "Redguard Lantern, Delicate",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:117817:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 117817,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2505899,
                                ["icon"] = "/esoui/art/icons/housing_red_lsb_hanginglanterninterior001.dds",
                                ["purchasePrice"] = 14250,
                            },
                            [27] = 
                            {
                                ["name"] = "Style Page: Morningstar Frostwear Epaulets",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199084:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 199084,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 82950,
                                ["timeRemaining"] = 2503954,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 82950,
                            },
                        },
                    },
                    ["guilds"] = 
                    {
                        [585680] = "Dro-m'Athra Traders",
                        [742682] = "Grim Bastion",
                        [147954] = "Polite and Nice",
                        [726298] = "Bandits Black Market",
                    },
                    ["active"] = 
                    {
                        [585680] = 
                        {
                        },
                        [147954] = 
                        {
                        },
                        [726298] = 
                        {
                            [1] = 
                            {
                                ["name"] = "Truly Superb Glyph of Prismatic Defense",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143407,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:68343:370:50:0:0:0:0:0:0:0:0:0:0:0:0:0:1:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 75000,
                                ["slotIndex"] = 1,
                                ["timeRemaining"] = 2478584,
                                ["icon"] = "/esoui/art/icons/crafting_enchantment_036.dds",
                                ["purchasePrice"] = 75000,
                            },
                            [2] = 
                            {
                                ["name"] = "Truly Superb Glyph of Prismatic Defense",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143407,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:68343:370:50:0:0:0:0:0:0:0:0:0:0:0:0:0:1:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 75000,
                                ["slotIndex"] = 2,
                                ["timeRemaining"] = 2478582,
                                ["icon"] = "/esoui/art/icons/crafting_enchantment_036.dds",
                                ["purchasePrice"] = 75000,
                            },
                            [3] = 
                            {
                                ["name"] = "Style Page: Morningstar Frostwear Shoes",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199085:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 70000,
                                ["slotIndex"] = 3,
                                ["timeRemaining"] = 2478506,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 70000,
                            },
                        },
                        [742682] = 
                        {
                            [1] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Tomeshell Viscera",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198388:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 3450,
                                ["slotIndex"] = 1,
                                ["timeRemaining"] = 2333726,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarscroll002.dds",
                                ["purchasePrice"] = 3450,
                            },
                            [2] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:679:29:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 401.7900000000,
                                ["slotIndex"] = 2,
                                ["timeRemaining"] = 2335859,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 44197,
                            },
                            [3] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:385:29:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 401.7900000000,
                                ["slotIndex"] = 3,
                                ["timeRemaining"] = 2335856,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 44197,
                            },
                            [4] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:540:23:0:0:0:0:0:0:0:0:0:897600|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 388.8900000000,
                                ["slotIndex"] = 4,
                                ["timeRemaining"] = 2335869,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 35000,
                            },
                            [5] = 
                            {
                                ["name"] = "Style Page: Y'ffre's Fallen-Wood Cuirass",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199053:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 22500,
                                ["slotIndex"] = 5,
                                ["timeRemaining"] = 2333693,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 22500,
                            },
                            [6] = 
                            {
                                ["name"] = "Style Page: Opal Velidreth Sword",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:190108:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 1950,
                                ["slotIndex"] = 6,
                                ["timeRemaining"] = 2333671,
                                ["icon"] = "/esoui/art/icons/quest_letter_002.dds",
                                ["purchasePrice"] = 1950,
                            },
                            [7] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Brains",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198382:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 4750,
                                ["slotIndex"] = 7,
                                ["timeRemaining"] = 2333744,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarbrains001.dds",
                                ["purchasePrice"] = 4750,
                            },
                            [8] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Centipede",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198383:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 3500,
                                ["slotIndex"] = 8,
                                ["timeRemaining"] = 2333750,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarcentipedes002.dds",
                                ["purchasePrice"] = 3500,
                            },
                            [9] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:71059:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["slotIndex"] = 9,
                                ["timeRemaining"] = 2335736,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [10] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:71059:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["slotIndex"] = 10,
                                ["timeRemaining"] = 2335738,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [11] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:64221:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["slotIndex"] = 11,
                                ["timeRemaining"] = 2335740,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [12] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:642:31:0:0:0:0:0:0:0:0:0:1122000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 401.7900000000,
                                ["slotIndex"] = 12,
                                ["timeRemaining"] = 2335848,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 45000,
                            },
                            [13] = 
                            {
                                ["name"] = "Sealed Clothier Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:121532:6:1:0:0:0:28:194:5:38:15:128:0:0:0:0:0:0:0:0:811200|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 250,
                                ["slotIndex"] = 13,
                                ["timeRemaining"] = 2335646,
                                ["icon"] = "/esoui/art/icons/master_writ_clothier.dds",
                                ["purchasePrice"] = 20250,
                            },
                            [14] = 
                            {
                                ["name"] = "Style Page: Nord Carved Gauntlets",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182469:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 2500,
                                ["slotIndex"] = 14,
                                ["timeRemaining"] = 2333685,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 2500,
                            },
                            [15] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:148:32:0:0:0:0:0:0:0:0:0:1122000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 401.7900000000,
                                ["slotIndex"] = 15,
                                ["timeRemaining"] = 2335851,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 45000,
                            },
                            [16] = 
                            {
                                ["name"] = "Style Page: Nord Carved Sabatons",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182467:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 7000,
                                ["slotIndex"] = 16,
                                ["timeRemaining"] = 2335809,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7000,
                            },
                            [17] = 
                            {
                                ["name"] = "Recipe: Lava Foot Soup-and-Saltrice",
                                ["quality"] = 3,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 3,
                                ["itemLink"] = "|H0:item:96967:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 27950,
                                ["slotIndex"] = 17,
                                ["timeRemaining"] = 2333625,
                                ["icon"] = "/esoui/art/icons/event_newlifefestival_2016_recipe.dds",
                                ["purchasePrice"] = 27950,
                            },
                            [18] = 
                            {
                                ["name"] = "Style Page: Nord Carved Pauldrons",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182466:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 7000,
                                ["slotIndex"] = 18,
                                ["timeRemaining"] = 2335815,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7000,
                            },
                            [19] = 
                            {
                                ["name"] = "Style Page: Nord Carved Cuirass",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182457:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 7500,
                                ["slotIndex"] = 19,
                                ["timeRemaining"] = 2335821,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [20] = 
                            {
                                ["name"] = "Breton Chamberstick, Short",
                                ["quality"] = 3,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 3,
                                ["itemLink"] = "|H0:item:116376:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 6250,
                                ["slotIndex"] = 20,
                                ["timeRemaining"] = 2335599,
                                ["icon"] = "/esoui/art/icons/housing_bre_lsb_candleholdershort001.dds",
                                ["purchasePrice"] = 6250,
                            },
                            [21] = 
                            {
                                ["name"] = "Redguard Lantern, Delicate",
                                ["quality"] = 4,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:117817:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 14250,
                                ["slotIndex"] = 21,
                                ["timeRemaining"] = 2335609,
                                ["icon"] = "/esoui/art/icons/housing_red_lsb_hanginglanterninterior001.dds",
                                ["purchasePrice"] = 14250,
                            },
                            [22] = 
                            {
                                ["name"] = "Style Page: Morningstar Frostwear Epaulets",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199084:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 82950,
                                ["slotIndex"] = 22,
                                ["timeRemaining"] = 2333664,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 82950,
                            },
                            [23] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:541:32:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 340.9100000000,
                                ["slotIndex"] = 23,
                                ["timeRemaining"] = 2478598,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 37500,
                            },
                            [24] = 
                            {
                                ["name"] = "Style Page: Nord Carved Girdle",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182470:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 2250,
                                ["slotIndex"] = 24,
                                ["timeRemaining"] = 2478586,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 2250,
                            },
                            [25] = 
                            {
                                ["name"] = "Style Page: Nord Carved Pauldrons",
                                ["quality"] = 5,
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182466:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["stackCount"] = 1,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["purchasePricePerUnit"] = 5000,
                                ["slotIndex"] = 25,
                                ["timeRemaining"] = 2478593,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 5000,
                            },
                        },
                    },
                    ["saved"] = 
                    {
                        [585680] = 
                        {
                            [1] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506303,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                            [2] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506304,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                            [3] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506305,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                        },
                        [147954] = 
                        {
                        },
                        [726298] = 
                        {
                            [4] = 
                            {
                                ["name"] = "Chromium Plating^n",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:203634:34:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 203634,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 8,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2506271,
                                ["icon"] = "/esoui/art/icons/jewelrycrafting_booster_refined_chromium.dds",
                                ["purchasePrice"] = 114000,
                            },
                            [1] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:153737:5:1:0:0:0:18:255:4:81:33:0:0:0:0:0:0:0:0:0:330750|h|h",
                                ["itemId"] = 153737,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 280,
                                ["timeRemaining"] = 2506218,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 9240,
                            },
                            [2] = 
                            {
                                ["name"] = "Kuta",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:45854:24:21:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 45854,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 25,
                                ["purchasePricePerUnit"] = 4250,
                                ["timeRemaining"] = 2506265,
                                ["icon"] = "/esoui/art/icons/crafting_components_runestones_001.dds",
                                ["purchasePrice"] = 106250,
                            },
                            [3] = 
                            {
                                ["name"] = "Kuta",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:45854:24:21:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 45854,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 25,
                                ["purchasePricePerUnit"] = 4250,
                                ["timeRemaining"] = 2506266,
                                ["icon"] = "/esoui/art/icons/crafting_components_runestones_001.dds",
                                ["purchasePrice"] = 106250,
                            },
                        },
                        [742682] = 
                        {
                            [1] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Tomeshell Viscera",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198388:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 198388,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3450,
                                ["timeRemaining"] = 2504016,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarscroll002.dds",
                                ["purchasePrice"] = 3450,
                            },
                            [2] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:679:29:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7910000000,
                                ["timeRemaining"] = 2506149,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 44197,
                            },
                            [3] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:323:21:0:0:0:0:0:0:0:0:0:880000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 363.6360000000,
                                ["timeRemaining"] = 2506168,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 32000,
                            },
                            [4] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:24:255:5:385:29:0:0:0:0:0:0:0:0:0:1100000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7910000000,
                                ["timeRemaining"] = 2506146,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 44197,
                            },
                            [5] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:540:23:0:0:0:0:0:0:0:0:0:897600|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 388.8890000000,
                                ["timeRemaining"] = 2506159,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 35000,
                            },
                            [6] = 
                            {
                                ["name"] = "Style Page: Y'ffre's Fallen-Wood Cuirass",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199053:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 199053,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 22500,
                                ["timeRemaining"] = 2503983,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 22500,
                            },
                            [7] = 
                            {
                                ["name"] = "Style Page: Opal Velidreth Sword",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:190108:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 190108,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 1950,
                                ["timeRemaining"] = 2503961,
                                ["icon"] = "/esoui/art/icons/quest_letter_002.dds",
                                ["purchasePrice"] = 1950,
                            },
                            [8] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Brains",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198382:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 198382,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 4750,
                                ["timeRemaining"] = 2504034,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarbrains001.dds",
                                ["purchasePrice"] = 4750,
                            },
                            [9] = 
                            {
                                ["name"] = "Apocrypha Specimen Jar, Centipede",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:198383:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 198383,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3500,
                                ["timeRemaining"] = 2504040,
                                ["icon"] = "/esoui/art/icons/housing_apc_inc_specimenjarcentipedes002.dds",
                                ["purchasePrice"] = 3500,
                            },
                            [10] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:71059:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["itemId"] = 119693,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["timeRemaining"] = 2506026,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [11] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:71059:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["itemId"] = 119693,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["timeRemaining"] = 2506028,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [12] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:153737:5:1:0:0:0:18:255:4:92:33:0:0:0:0:0:0:0:0:0:346500|h|h",
                                ["itemId"] = 153737,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 280,
                                ["timeRemaining"] = 2506186,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 9800,
                            },
                            [13] = 
                            {
                                ["name"] = "Sealed Provisioning Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119693:5:1:0:0:0:64221:0:0:0:0:0:0:0:0:0:0:0:0:0:400000|h|h",
                                ["itemId"] = 119693,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 187.5000000000,
                                ["timeRemaining"] = 2506030,
                                ["icon"] = "/esoui/art/icons/master_writ_provisioning.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [14] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:642:31:0:0:0:0:0:0:0:0:0:1122000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7860000000,
                                ["timeRemaining"] = 2506138,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 45000,
                            },
                            [15] = 
                            {
                                ["name"] = "Sealed Alchemy Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119703:5:1:0:0:0:199:8:11:2:0:0:0:0:0:0:0:0:0:0:50000|h|h",
                                ["itemId"] = 119703,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3400,
                                ["timeRemaining"] = 2506042,
                                ["icon"] = "/esoui/art/icons/master_writ_alchemy.dds",
                                ["purchasePrice"] = 17000,
                            },
                            [16] = 
                            {
                                ["name"] = "Sealed Alchemy Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119819:5:1:0:0:0:199:18:10:2:0:0:0:0:0:0:0:0:0:0:50000|h|h",
                                ["itemId"] = 119819,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3400,
                                ["timeRemaining"] = 2506048,
                                ["icon"] = "/esoui/art/icons/master_writ_alchemy.dds",
                                ["purchasePrice"] = 17000,
                            },
                            [17] = 
                            {
                                ["name"] = "Sealed Clothier Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:121532:6:1:0:0:0:28:194:5:38:15:128:0:0:0:0:0:0:0:0:811200|h|h",
                                ["itemId"] = 121532,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 250,
                                ["timeRemaining"] = 2505936,
                                ["icon"] = "/esoui/art/icons/master_writ_clothier.dds",
                                ["purchasePrice"] = 20250,
                            },
                            [18] = 
                            {
                                ["name"] = "Sealed Alchemy Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:119696:5:1:0:0:0:199:2:11:21:0:0:0:0:0:0:0:0:0:0:50000|h|h",
                                ["itemId"] = 119696,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 3400,
                                ["timeRemaining"] = 2506056,
                                ["icon"] = "/esoui/art/icons/master_writ_alchemy.dds",
                                ["purchasePrice"] = 17000,
                            },
                            [19] = 
                            {
                                ["name"] = "Style Page: Nord Carved Gauntlets",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182469:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182469,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 2500,
                                ["timeRemaining"] = 2503975,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 2500,
                            },
                            [20] = 
                            {
                                ["name"] = "Sealed Jewelry Crafter Writ",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:153738:6:1:0:0:0:18:255:5:148:32:0:0:0:0:0:0:0:0:0:1122000|h|h",
                                ["itemId"] = 153738,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 401.7860000000,
                                ["timeRemaining"] = 2506141,
                                ["icon"] = "/esoui/art/icons/master_writ_jewelry.dds",
                                ["purchasePrice"] = 45000,
                            },
                            [21] = 
                            {
                                ["name"] = "Style Page: Nord Carved Sabatons",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182467:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182467,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 7000,
                                ["timeRemaining"] = 2506099,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7000,
                            },
                            [22] = 
                            {
                                ["name"] = "Recipe: Lava Foot Soup-and-Saltrice",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 3,
                                ["itemLink"] = "|H0:item:96967:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 96967,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 27950,
                                ["timeRemaining"] = 2503915,
                                ["icon"] = "/esoui/art/icons/event_newlifefestival_2016_recipe.dds",
                                ["purchasePrice"] = 27950,
                            },
                            [23] = 
                            {
                                ["name"] = "Style Page: Nord Carved Pauldrons",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182466:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182466,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 7000,
                                ["timeRemaining"] = 2506105,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7000,
                            },
                            [24] = 
                            {
                                ["name"] = "Style Page: Nord Carved Cuirass",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:182457:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 182457,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 7500,
                                ["timeRemaining"] = 2506111,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 7500,
                            },
                            [25] = 
                            {
                                ["name"] = "Breton Chamberstick, Short",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 3,
                                ["itemLink"] = "|H0:item:116376:4:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 116376,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 6250,
                                ["timeRemaining"] = 2505889,
                                ["icon"] = "/esoui/art/icons/housing_bre_lsb_candleholdershort001.dds",
                                ["purchasePrice"] = 6250,
                            },
                            [26] = 
                            {
                                ["name"] = "Redguard Lantern, Delicate",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 4,
                                ["itemLink"] = "|H0:item:117817:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 117817,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 14250,
                                ["timeRemaining"] = 2505899,
                                ["icon"] = "/esoui/art/icons/housing_red_lsb_hanginglanterninterior001.dds",
                                ["purchasePrice"] = 14250,
                            },
                            [27] = 
                            {
                                ["name"] = "Style Page: Morningstar Frostwear Epaulets",
                                ["itemUniqueId"] = 2.8357143408,
                                ["displayQuality"] = 5,
                                ["itemLink"] = "|H0:item:199084:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                                ["itemId"] = 199084,
                                ["currencyType"] = 1,
                                ["sellerName"] = "@ventrill",
                                ["stackCount"] = 1,
                                ["purchasePricePerUnit"] = 82950,
                                ["timeRemaining"] = 2503954,
                                ["icon"] = "/esoui/art/icons/quest_summerset_completed_report.dds",
                                ["purchasePrice"] = 82950,
                            },
                        },
                    },
                },
            },
        },
    },
}
